[package]
name = "char_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recursion = "0.3.2"
static_assertions = "1.1.0"
